// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	oauth2 "golang.org/x/oauth2"
)

// OAuthReadWriter is an autogenerated mock type for the OAuthReadWriter type
type OAuthReadWriter struct {
	mock.Mock
}

// GetTokenInfo provides a mock function with given fields: userUUID
func (_m *OAuthReadWriter) GetTokenInfo(userUUID string) (*oauth2.Token, error) {
	ret := _m.Called(userUUID)

	var r0 *oauth2.Token
	if rf, ok := ret.Get(0).(func(string) *oauth2.Token); ok {
		r0 = rf(userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteTokenInfo provides a mock function with given fields: userUUID, token
func (_m *OAuthReadWriter) WriteTokenInfo(userUUID string, token *oauth2.Token) error {
	ret := _m.Called(userUUID, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *oauth2.Token) error); ok {
		r0 = rf(userUUID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
