apiVersion: skaffold/v2beta1
kind: Config

build:
  local:
    push: true
  artifacts:
    - image: learnalist
      context: ./server
      docker:
        dockerfile: Dockerfile_dev
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - k8s/leanralist.yaml
