apiVersion: v1
kind: PersistentVolume
metadata:
  name: remind-daily-01-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: "Filesystem"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/srv/remind-daily"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remind-daily-01-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: remind-daily-01-pv-volume
