baseURL = ""
languageCode = "en-us"
title = "Learnalist"

uglyURLs = true
disableKinds=["home", "sitemap", "taxonomy", "taxonomyTerm", "RSS"]

[params]
  ApiServer = "http://localhost:1234"
  #ApiServer = "https://learnalist.net"

[taxonomies]
  label = "labels"

[output]
alist = ["HTML"]

#[build]
#  useResourceCacheWhen = "always"

[markup.goldmark.renderer]
  unsafe = true
