// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import user "github.com/freshteapot/learnalist-api/server/pkg/user"

// UserFromIDP is an autogenerated mock type for the UserFromIDP type
type UserFromIDP struct {
	mock.Mock
}

// GetByUserUUID provides a mock function with given fields: userUUID
func (_m *UserFromIDP) GetByUserUUID(userUUID string) (user.UserInfoFromIDP, error) {
	ret := _m.Called(userUUID)

	var r0 user.UserInfoFromIDP
	if rf, ok := ret.Get(0).(func(string) user.UserInfoFromIDP); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Get(0).(user.UserInfoFromIDP)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lookup provides a mock function with given fields: idp, identifier
func (_m *UserFromIDP) Lookup(idp string, identifier string) (string, error) {
	ret := _m.Called(idp, identifier)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(idp, identifier)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(idp, identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: idp, identifier, info
func (_m *UserFromIDP) Register(idp string, identifier string, info []byte) (string, error) {
	ret := _m.Called(idp, identifier, info)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, []byte) string); ok {
		r0 = rf(idp, identifier, info)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, []byte) error); ok {
		r1 = rf(idp, identifier, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
