staticsite:
  directory: "./../hugo"
  external: "true"
hugo:
  directory: "./../hugo"
  environment: "dev"
  external: "true"
remind:
  daily:
    sqlite:
      database: /tmp/learnalist/remind-daily.db
server:
  assets:
    directory: "/tmp/learnalist/assets"
  sqlite:
    database: /tmp/learnalist/server.db
  fcm:
    credentials: ./../secrets/fcm-credentials.json
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
      audiences:
        - XXX
    appleID:
      web:
        clientID: "XXX"
        cert: |
          -----BEGIN PRIVATE KEY-----
          XXX
          -----END PRIVATE KEY-----
        server: "http://localhost:1234"
        teamID: "XXX"
        keyID: "XXX"
      apps: []
        # Array of AppleConfig objects, same as server.loginWith.appleID.web
  userRegisterKey: ""
tools:
  integrationTests:
    username: ""
    password: ""
    server: ""
