hugo:
  directory: "./../hugo"
  environment: "dev"
  external: "true"

server:
  assets:
    directory: "/tmp/learnalist/assets"
  sqlite:
    database: /tmp/learnalist/server.db
  fcm:
    credentials: ./../secrets/fcm-credentials.json
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
    idp:
      issuedTo:
        - "XXX"
  userRegisterKey: ""
tools:
  integrationTests:
    username: ""
    password: ""
    server: ""
