hugo:
  directory: "./../hugo"
  environment: "dev"
  external: "true"

server:
  sqlite:
    database: /tmp/learnalist/server.db
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
tools:
  rebuildStaticSite:
    sqlite:
      database: /tmp/learnalist/server.db
  integrationTests:
    username: ""
    password: ""
    server: ""
