server:
  sqlite:
    database: /tmp/learnalist-api/server.db
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  siteCacheDirectory: /tmp/learnalist-api/site-cache
  hugo:
    directory: "./../hugo"
    environment: "dev"

  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
tools:
  rebuildStaticSite:
    sqlite:
      database: /tmp/learnalist-api/server.db
    siteCacheDirectory: /tmp/learnalist-api/site-cache
    hugo:
      directory: "./../hugo"
      environment: "dev"
  integrationTests:
    username: ""
    password: ""
    server: ""
