hugo:
  directory: "/srv/learnalist/hugo"
  environment: "docker"
  external: "true"
server:
  sqlite:
    database: /srv/learnalist/server.db
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
tools:
  rebuildStaticSite:
    sqlite:
      database: /srv/learnalist/server.db
  integrationTests:
    username: ""
    password: ""
    server: ""
