server:
  sqlite:
    database: /srv/learnalist/server.db
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  siteCacheDirectory: /srv/learnalist/hugo/public
  hugo:
    directory: "/srv/learnalist/hugo"
    environment: "docker"

  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
tools:
  rebuildStaticSite:
    sqlite:
      database: /srv/learnalist/server.db
    siteCacheDirectory: /srv/learnalist/hugo/public
    hugo:
      directory: "/srv/learnalist/hugo"
      environment: "docker"
  integrationTests:
    username: ""
    password: ""
    server: ""
