hugo:
  directory: "/srv/learnalist/hugo"
  environment: "docker"
  external: "true"
remind:
  daily:
    sqlite:
      database: /srv/remind-daily/remind-daily.db
server:
  assets:
    directory: "/srv/learnalist/assets"
  sqlite:
    database: /srv/learnalist/server.db
  fcm:
    credentials: /srv/learnalist/config/fcm-credentials.json
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "localhost"
    secure: false
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "http://localhost:1234"
    idp:
      issuedTo:
        - "XXX"
  userRegisterKey: ""
tools:
  integrationTests:
    username: ""
    password: ""
    server: ""
