hugo:
  directory: "/srv/learnalist/hugo"
  environment: "lal01"
  external: "false"

server:
  assets:
    directory: "/srv/learnalist/assets"
  sqlite:
    database: /srv/learnalist/server.db
  fcm:
    credentials: /srv/learnalist/config/fcm-credentials.json
  port: "1234"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "learnalist.net"
    secure: true
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "https://learnalist.net"

tools:
  integrationTests:
    username: ""
    password: ""
    server: ""
