server:
  sqlite:
    database: "/srv/learnalist/api.db"
  port: "9090"
  cors:
    allowedOrigins: "*"
  cookie:
    domain: "learnalist.net"
    secure: true
  siteCacheDirectory: "/srv/learnalist/site-cache"
  hugo:
    directory: "/srv/learnalist/hugo"
    environment: "production"
  loginWith:
    google:
      clientID: "XXX"
      clientSecret: "XXX"
      server: "https://learnalist.net"

tools:
  rebuildStaticSite:
    sqlite:
      database: "/srv/learnalist/api.db"
    siteCacheDirectory: "/srv/learnalist/site-cache"
    hugo:
      directory: "/srv/learnalist/hugo"
      environment: "production"
  integrationTests:
    username: ""
    password: ""
    server: ""
