baseURL = "https://learnalist.net/"
languageCode = "en-us"
title = "Alists"
theme = "alist"

uglyURLs=true
publishDir="public-alist"

# Without section, gives us a nice index page
disableKinds=["404", "home", "sitemap", "taxonomy", "taxonomyTerm", "RSS"]

[outputs]
    page = ["HTML", "JSON"]
