// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	alist "github.com/freshteapot/learnalist-api/server/api/alist"
	mock "github.com/stretchr/testify/mock"
)

// DatastoreAlists is an autogenerated mock type for the DatastoreAlists type
type DatastoreAlists struct {
	mock.Mock
}

// GetAlist provides a mock function with given fields: uuid
func (_m *DatastoreAlists) GetAlist(uuid string) (*alist.Alist, error) {
	ret := _m.Called(uuid)

	var r0 *alist.Alist
	if rf, ok := ret.Get(0).(func(string) *alist.Alist); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alist.Alist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListsByUserWithFilters provides a mock function with given fields: uuid, labels, listType
func (_m *DatastoreAlists) GetListsByUserWithFilters(uuid string, labels string, listType string) []*alist.Alist {
	ret := _m.Called(uuid, labels, listType)

	var r0 []*alist.Alist
	if rf, ok := ret.Get(0).(func(string, string, string) []*alist.Alist); ok {
		r0 = rf(uuid, labels, listType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*alist.Alist)
		}
	}

	return r0
}

// GetUserLabels provides a mock function with given fields: uuid
func (_m *DatastoreAlists) GetUserLabels(uuid string) ([]string, error) {
	ret := _m.Called(uuid)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAlist provides a mock function with given fields: alist_uuid, user_uuid
func (_m *DatastoreAlists) RemoveAlist(alist_uuid string, user_uuid string) error {
	ret := _m.Called(alist_uuid, user_uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(alist_uuid, user_uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAlist provides a mock function with given fields: method, aList
func (_m *DatastoreAlists) SaveAlist(method string, aList alist.Alist) (*alist.Alist, error) {
	ret := _m.Called(method, aList)

	var r0 *alist.Alist
	if rf, ok := ret.Get(0).(func(string, alist.Alist) *alist.Alist); ok {
		r0 = rf(method, aList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alist.Alist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, alist.Alist) error); ok {
		r1 = rf(method, aList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
