// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclAsset is an autogenerated mock type for the AclAsset type
type AclAsset struct {
	mock.Mock
}

// DeleteAsset provides a mock function with given fields: extUUID
func (_m *AclAsset) DeleteAsset(extUUID string) error {
	ret := _m.Called(extUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GrantUserAssetReadAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclAsset) GrantUserAssetReadAccess(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasUserAssetReadAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclAsset) HasUserAssetReadAccess(extUUID string, userUUID string) (bool, error) {
	ret := _m.Called(extUUID, userUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(extUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsListPrivate provides a mock function with given fields: extUUID
func (_m *AclAsset) IsListPrivate(extUUID string) (bool, error) {
	ret := _m.Called(extUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(extUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsListPublic provides a mock function with given fields: extUUID
func (_m *AclAsset) IsListPublic(extUUID string) (bool, error) {
	ret := _m.Called(extUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(extUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeAssetPrivate provides a mock function with given fields: extUUID, userUUID
func (_m *AclAsset) MakeAssetPrivate(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeUserAssetReadAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclAsset) RevokeUserAssetReadAccess(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShareAssetWithPublic provides a mock function with given fields: extUUID
func (_m *AclAsset) ShareAssetWithPublic(extUUID string) error {
	ret := _m.Called(extUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
