// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclChallenge is an autogenerated mock type for the AclChallenge type
type AclChallenge struct {
	mock.Mock
}

// DeleteChallenge provides a mock function with given fields: extUUID
func (_m *AclChallenge) DeleteChallenge(extUUID string) error {
	ret := _m.Called(extUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GrantUserChallengeWriteAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclChallenge) GrantUserChallengeWriteAccess(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasUserChallengeOwnerAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclChallenge) HasUserChallengeOwnerAccess(extUUID string, userUUID string) (bool, error) {
	ret := _m.Called(extUUID, userUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(extUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasUserChallengeWriteAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclChallenge) HasUserChallengeWriteAccess(extUUID string, userUUID string) (bool, error) {
	ret := _m.Called(extUUID, userUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(extUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeChallengePrivate provides a mock function with given fields: extUUID, userUUID
func (_m *AclChallenge) MakeChallengePrivate(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeUserChallengeWriteAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclChallenge) RevokeUserChallengeWriteAccess(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShareChallengeWithPublic provides a mock function with given fields: extUUID
func (_m *AclChallenge) ShareChallengeWithPublic(extUUID string) error {
	ret := _m.Called(extUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
