// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclPlankHistory is an autogenerated mock type for the AclPlankHistory type
type AclPlankHistory struct {
	mock.Mock
}

// IsPlankHistoryPublic provides a mock function with given fields: extUUID
func (_m *AclPlankHistory) IsPlankHistoryPublic(extUUID string) (bool, error) {
	ret := _m.Called(extUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(extUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakePlankHistoryPrivate provides a mock function with given fields: userUUID
func (_m *AclPlankHistory) MakePlankHistoryPrivate(userUUID string) error {
	ret := _m.Called(userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SharePlankHistoryWithPublic provides a mock function with given fields: extUUID
func (_m *AclPlankHistory) SharePlankHistoryWithPublic(extUUID string) error {
	ret := _m.Called(extUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
