// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclPlankHistory is an autogenerated mock type for the AclPlankHistory type
type AclPlankHistory struct {
	mock.Mock
}

// GrantUserPlankHistoryReadAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclPlankHistory) GrantUserPlankHistoryReadAccess(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasUserPlankHistoryReadAccess provides a mock function with given fields: alistUUID, userUUID
func (_m *AclPlankHistory) HasUserPlankHistoryReadAccess(alistUUID string, userUUID string) (bool, error) {
	ret := _m.Called(alistUUID, userUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(alistUUID, userUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(alistUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakePlankHistoryPrivate provides a mock function with given fields: userUUID
func (_m *AclPlankHistory) MakePlankHistoryPrivate(userUUID string) error {
	ret := _m.Called(userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeUserPlankHistoryReadAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclPlankHistory) RevokeUserPlankHistoryReadAccess(extUUID string, userUUID string) error {
	ret := _m.Called(extUUID, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SharePlankHistoryWithPublic provides a mock function with given fields: extUUID
func (_m *AclPlankHistory) SharePlankHistoryWithPublic(extUUID string) error {
	ret := _m.Called(extUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
