// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclReaderPlankHistory is an autogenerated mock type for the AclReaderPlankHistory type
type AclReaderPlankHistory struct {
	mock.Mock
}

// HasUserPlankHistoryReadAccess provides a mock function with given fields: alistUUID, userUUID
func (_m *AclReaderPlankHistory) HasUserPlankHistoryReadAccess(alistUUID string, userUUID string) (bool, error) {
	ret := _m.Called(alistUUID, userUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(alistUUID, userUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(alistUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
