// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclReaderPlankHistory is an autogenerated mock type for the AclReaderPlankHistory type
type AclReaderPlankHistory struct {
	mock.Mock
}

// IsPlankHistoryPublic provides a mock function with given fields: extUUID
func (_m *AclReaderPlankHistory) IsPlankHistoryPublic(extUUID string) (bool, error) {
	ret := _m.Called(extUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(extUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
