// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AclReaderAsset is an autogenerated mock type for the AclReaderAsset type
type AclReaderAsset struct {
	mock.Mock
}

// HasUserAssetReadAccess provides a mock function with given fields: extUUID, userUUID
func (_m *AclReaderAsset) HasUserAssetReadAccess(extUUID string, userUUID string) (bool, error) {
	ret := _m.Called(extUUID, userUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(extUUID, userUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(extUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsListPrivate provides a mock function with given fields: extUUID
func (_m *AclReaderAsset) IsListPrivate(extUUID string) (bool, error) {
	ret := _m.Called(extUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(extUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsListPublic provides a mock function with given fields: extUUID
func (_m *AclReaderAsset) IsListPublic(extUUID string) (bool, error) {
	ret := _m.Called(extUUID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(extUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(extUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
