// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	event "github.com/freshteapot/learnalist-api/server/pkg/event"
	mock "github.com/stretchr/testify/mock"
)

// EventlogPubSub is an autogenerated mock type for the EventlogPubSub type
type EventlogPubSub struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *EventlogPubSub) Close() {
	_m.Called()
}

// Publish provides a mock function with given fields: moment
func (_m *EventlogPubSub) Publish(moment event.Eventlog) {
	_m.Called(moment)
}

// Start provides a mock function with given fields:
func (_m *EventlogPubSub) Start() {
	_m.Called()
}

// Subscribe provides a mock function with given fields: key, fn
func (_m *EventlogPubSub) Subscribe(key string, fn interface{}) {
	_m.Called(key, fn)
}

// Unsubscribe provides a mock function with given fields: key
func (_m *EventlogPubSub) Unsubscribe(key string) {
	_m.Called(key)
}
