// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	event "github.com/freshteapot/learnalist-api/server/pkg/event"
	mock "github.com/stretchr/testify/mock"
)

// EventlogPubSub is an autogenerated mock type for the EventlogPubSub type
type EventlogPubSub struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *EventlogPubSub) Close() {
	_m.Called()
}

// Publish provides a mock function with given fields: topic, moment
func (_m *EventlogPubSub) Publish(topic string, moment event.Eventlog) {
	_m.Called(topic, moment)
}

// Start provides a mock function with given fields: topic
func (_m *EventlogPubSub) Start(topic string) {
	_m.Called(topic)
}

// Subscribe provides a mock function with given fields: topic, key, fn
func (_m *EventlogPubSub) Subscribe(topic string, key string, fn interface{}) {
	_m.Called(topic, key, fn)
}

// Unsubscribe provides a mock function with given fields: topic, key
func (_m *EventlogPubSub) Unsubscribe(topic string, key string) {
	_m.Called(topic, key)
}
