// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileWriter is an autogenerated mock type for the FileWriter type
type FileWriter struct {
	mock.Mock
}

// Remove provides a mock function with given fields: path
func (_m *FileWriter) Remove(path string) {
	_m.Called(path)
}

// Write provides a mock function with given fields: path, data
func (_m *FileWriter) Write(path string, data []byte) {
	_m.Called(path, data)
}
