// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	alist "github.com/freshteapot/learnalist-api/server/api/alist"

	mock "github.com/stretchr/testify/mock"
)

// HugoSiteBuilder is an autogenerated mock type for the HugoSiteBuilder type
type HugoSiteBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *HugoSiteBuilder) Build() {
	_m.Called()
}

// DeleteList provides a mock function with given fields: uuid
func (_m *HugoSiteBuilder) DeleteList(uuid string) error {
	ret := _m.Called(uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: uuid
func (_m *HugoSiteBuilder) DeleteUser(uuid string) error {
	ret := _m.Called(uuid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessContent provides a mock function with given fields:
func (_m *HugoSiteBuilder) ProcessContent() {
	_m.Called()
}

// WriteList provides a mock function with given fields: aList
func (_m *HugoSiteBuilder) WriteList(aList alist.Alist) {
	_m.Called(aList)
}

// WriteListsByUser provides a mock function with given fields: userUUID, lists
func (_m *HugoSiteBuilder) WriteListsByUser(userUUID string, lists []alist.ShortInfo) {
	_m.Called(userUUID, lists)
}

// WritePublicLists provides a mock function with given fields: lists
func (_m *HugoSiteBuilder) WritePublicLists(lists []alist.ShortInfo) {
	_m.Called(lists)
}
