// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"
)

// Insights is an autogenerated mock type for the Insights type
type Insights struct {
	mock.Mock
}

// Event provides a mock function with given fields: fields
func (_m *Insights) Event(fields logrus.Fields) {
	_m.Called(fields)
}
