// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ManagementSite is an autogenerated mock type for the ManagementSite type
type ManagementSite struct {
	mock.Mock
}

// DeleteList provides a mock function with given fields: listUUID
func (_m *ManagementSite) DeleteList(listUUID string) error {
	ret := _m.Called(listUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(listUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: userUUID
func (_m *ManagementSite) DeleteUser(userUUID string) error {
	ret := _m.Called(userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
