// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MobileRepository is an autogenerated mock type for the MobileRepository type
type MobileRepository struct {
	mock.Mock
}

// DeleteByUser provides a mock function with given fields: userUUID
func (_m *MobileRepository) DeleteByUser(userUUID string) error {
	ret := _m.Called(userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveDeviceInfo provides a mock function with given fields: userUUID, token
func (_m *MobileRepository) SaveDeviceInfo(userUUID string, token string) error {
	ret := _m.Called(userUUID, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userUUID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
