// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	openapi "github.com/freshteapot/learnalist-api/server/pkg/openapi"
	mock "github.com/stretchr/testify/mock"
)

// MobileRepository is an autogenerated mock type for the MobileRepository type
type MobileRepository struct {
	mock.Mock
}

// DeleteByUser provides a mock function with given fields: userUUID
func (_m *MobileRepository) DeleteByUser(userUUID string) error {
	ret := _m.Called(userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveDeviceInfo provides a mock function with given fields: userUUID, input
func (_m *MobileRepository) SaveDeviceInfo(userUUID string, input openapi.HttpMobileRegisterInput) (int, error) {
	ret := _m.Called(userUUID, input)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, openapi.HttpMobileRegisterInput) int); ok {
		r0 = rf(userUUID, input)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, openapi.HttpMobileRegisterInput) error); ok {
		r1 = rf(userUUID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
