// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	stripe "github.com/stripe/stripe-go/v71"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ID
func (_m *PaymentRepository) Get(ID string) (stripe.Event, error) {
	ret := _m.Called(ID)

	var r0 stripe.Event
	if rf, ok := ret.Get(0).(func(string) stripe.Event); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(stripe.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: event
func (_m *PaymentRepository) Save(event stripe.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(stripe.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
