// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	time "time"

	remind "github.com/freshteapot/learnalist-api/server/pkg/remind"
	mock "github.com/stretchr/testify/mock"
)

// RemindSpacedRepetitionRepository is an autogenerated mock type for the RemindSpacedRepetitionRepository type
type RemindSpacedRepetitionRepository struct {
	mock.Mock
}

// DeleteByUser provides a mock function with given fields: userUUID
func (_m *RemindSpacedRepetitionRepository) DeleteByUser(userUUID string) error {
	ret := _m.Called(userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetReminders provides a mock function with given fields: whenNext, lastActive
func (_m *RemindSpacedRepetitionRepository) GetReminders(whenNext string, lastActive string) ([]remind.SpacedRepetitionReminder, error) {
	ret := _m.Called(whenNext, lastActive)

	var r0 []remind.SpacedRepetitionReminder
	if rf, ok := ret.Get(0).(func(string, string) []remind.SpacedRepetitionReminder); ok {
		r0 = rf(whenNext, lastActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]remind.SpacedRepetitionReminder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(whenNext, lastActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPushEnabled provides a mock function with given fields: userUUID, enabled
func (_m *RemindSpacedRepetitionRepository) SetPushEnabled(userUUID string, enabled int32) error {
	ret := _m.Called(userUUID, enabled)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int32) error); ok {
		r0 = rf(userUUID, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetReminder provides a mock function with given fields: userUUID, whenNext, lastActive
func (_m *RemindSpacedRepetitionRepository) SetReminder(userUUID string, whenNext time.Time, lastActive time.Time) error {
	ret := _m.Called(userUUID, whenNext, lastActive)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) error); ok {
		r0 = rf(userUUID, whenNext, lastActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSent provides a mock function with given fields: userUUID, sent
func (_m *RemindSpacedRepetitionRepository) UpdateSent(userUUID string, sent int) error {
	ret := _m.Called(userUUID, sent)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(userUUID, sent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
