// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	assets "github.com/freshteapot/learnalist-api/server/pkg/assets"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SaveEntry provides a mock function with given fields: entry
func (_m *Repository) SaveEntry(entry assets.AssetEntry) error {
	ret := _m.Called(entry)

	var r0 error
	if rf, ok := ret.Get(0).(func(assets.AssetEntry) error); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
