// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	user "github.com/freshteapot/learnalist-api/server/pkg/user"
	mock "github.com/stretchr/testify/mock"
)

// UserInfoRepository is an autogenerated mock type for the UserInfoRepository type
type UserInfoRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: userUUID
func (_m *UserInfoRepository) Get(userUUID string) (user.UserPreference, error) {
	ret := _m.Called(userUUID)

	var r0 user.UserPreference
	if rf, ok := ret.Get(0).(func(string) user.UserPreference); ok {
		r0 = rf(userUUID)
	} else {
		r0 = ret.Get(0).(user.UserPreference)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: userUUID, pref
func (_m *UserInfoRepository) Save(userUUID string, pref user.UserPreference) error {
	ret := _m.Called(userUUID, pref)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, user.UserPreference) error); ok {
		r0 = rf(userUUID, pref)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
